name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
      fail-fast: false  # 防止一个版本失败时取消其他版本

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 Python 环境
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black autoflake pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 运行 black 格式化
      - name: Run black
        run: |
          black . --line-length=88

      # 运行 autoflake 删除未使用导入
      - name: Run autoflake
        run: |
          autoflake --in-place --remove-all-unused-imports .

      # 提交格式化更改
      - name: Commit formatting changes
        if: github.event_name == 'push'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Apply black and autoflake formatting" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 检查测试文件是否存在
      - name: Check for test files
        run: |
          find . -name "test_*.py" -o -name "*_test.py" || echo "No test files found"

      # 运行测试
      - name: Run tests
        run: |
          pytest tests/ --verbose || echo "Pytest failed or no tests collected"
