name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        
    - name: Build package
      run: python setup.py sdist bdist_wheel
        
    - name: Install package
      run: pip install .
        
    - name: Run basic tests
      run: |
        python -c "from EnigmaEnhanced import __version__; print(f'Version: {__version__}')"
        python -c "from EnigmaEnhanced.core import EnigmaEnhanced; enigma = EnigmaEnhanced()"
