name: Close stale issues

on:
  schedule:
    - cron: "0 0 * * *" # 每天 UTC 0 点运行

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v9
      with:
        days-before-stale: 60
        days-before-close: 7
        stale-issue-message: "This issue has been inactive for 60 days. It will be closed in 7 days unless activity resumes."
        stale-issue-label: "stale"
        exempt-issue-labels: "keep-open"
        close-issue-message: "This issue was closed due to inactivity."
